export enum CodeAssistErrorType {
  UNKNOWN = "UNKNOWN",

  STAT_ERROR = "STAT_ERROR",
  READ_ERROR = "READ_ERROR",

  LOAD_ERROR = "LOAD_ERROR",
  PARSE_ERROR = "PARSE_ERROR",

  MATCHER_ENGINE_INITIALIZATION_ERROR = "MATCHER_ENGINE_INITIALIZATION_ERROR",

  AUGMENTATION_ERROR = "AUGMENTATION_ERROR",
  MATCH_ERROR = "MATCH_ERROR",
  MATCH_PROCESSING_ERROR = "MATCH_PROCESSING_ERROR",
  TRANSFORM_ERROR = "TRANSFORM_ERROR",

  PRINT_ERROR = "PRINT_ERROR",
  WRITE_ERROR = "WRITE_ERROR",
  DIFF_ERROR = "DIFF_ERROR",

  FILE_TOO_LARGE = "FILE_TOO_LARGE",
  DIFF_TOO_LARGE = "DIFF_TOO_LARGE",
}
